apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: us-east-1

# nodeGroups:
#   - name: ng-1
#     instanceType: m5.large
#     desiredCapacity: 10
#   - name: ng-2
#     instanceType: m5.xlarge
#     desiredCapacity: 2

managedNodeGroups:
- name: expense
  instanceType: m5.large
  desiredCapacity: 3
  spot: true


#EKSCTL install
  #curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  #sudo mv /tmp/eksctl /usr/local/bin
  #eksctl version

#Kubectl Install
#curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.0/2024-05-12/bin/linux/amd64/kubectl
#chmod +x ./kubectl
#sudo mv kubectl /usr/local/bin
#kubectl version --client

#aws configure
#eksctl create cluster --config-file=eks.yaml

