apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: us-east-1

# nodeGroups:
#   - name: ng-1
#     instanceType: m5.large
#     desiredCapacity: 10
#   - name: ng-2
#     instanceType: m5.xlarge
#     desiredCapacity: 2

manageNodeGroups:
- name: expense
  instanceType: m5.large
  desiredCapacity: 3
  spot: true